#!/bin/sh
#File:  MyBundle.app/Contents/MacOS/Run
mypath=`dirname "$0"`
echo $mypath
export DYLD_LIBRARY_PATH=$mypath
$mypath/rocview -i rocdata/rocview.ini -t $mypath/../../../rocdata/trace/rocview.trace -sp $mypath
