#ifndef __mgv141dlg__
#define __mgv141dlg__

/**
@file
Subclass of mgv141gen, which is generated by wxFormBuilder.
*/

#include "mgv141dlggen.h"

#include "rocs/public/node.h"

/** Implementing mgv141gen */
class MGV141Dlg : public mgv141gen
{
protected:
	// Handlers for mgv141gen events.
	void onUnitSet( wxCommandEvent& event );
	void onWriteAll( wxCommandEvent& event );
	void onReadAll( wxCommandEvent& event );
	void onCancel( wxCommandEvent& event );
	void onOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	MGV141Dlg( wxWindow* parent );
};

#endif // __mgv141dlg__
