/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2013 Rob Versluis, Rocrail.net

 Without an official permission commercial use is not permitted.
 Forking this project is not permitted.

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef __rocnetnodedlg__
#define __rocnetnodedlg__

/**
@file
Subclass of rocnetnodegen, which is generated by wxFormBuilder.
*/

#include "rocnetnodegen.h"

//// end generated include
#include "rocs/public/node.h"

/** Implementing rocnetnodegen */
class RocnetNodeDlg : public rocnetnodegen
{
  iONode m_Ini;
  iONode m_Digint;
  iONode m_Props;
  void initLabels();
  void initValues();
  void initNodeList();
  void initPorts();
  int m_PortGroup;

	protected:
		// Handlers for rocnetnodegen events.
    void onIndexSelected( wxListEvent& event );
		void onRocnetWrite( wxCommandEvent& event );
		void onPortPrev( wxCommandEvent& event );
		void onPortNext( wxCommandEvent& event );
		void onPortRead( wxCommandEvent& event );
		void onPortWrite( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onClose( wxCloseEvent& event );
		void onNodeOptionsRead( wxCommandEvent& event );
		void onNodeOptionsWrite( wxCommandEvent& event );
		void onShutdown( wxCommandEvent& event );
    void onShutdownAll( wxCommandEvent& event );
	public:
		/** Constructor */
		RocnetNodeDlg( wxWindow* parent, iONode ini );
	//// end generated class members
		void event(iONode node);
	
};

#endif // __rocnetnodedlg__
