/*
 Copyright (C) 2002-2012 Rob Versluis, Rocrail.net

 Without an official permission commercial use is not permitted.
 Forking this project is not permitted.
 */
#ifndef __uhl633x0dlg__
#define __uhl633x0dlg__

/**
@file
Subclass of uhl633x0dlggen, which is generated by wxFormBuilder.
*/

#include "uhl633x0gen.h"
#include "wx/timer.h"

#include "rocs/public/node.h"
#include "rocs/public/queue.h"

#define LNCV_Timer 10199



/** Implementing uhl633x0dlggen */
class Uhl633x0Dlg : public uhl633x0dlggen
{
public:
	/** Constructor */
	Uhl633x0Dlg( wxWindow* parent );
  void event( iONode event );
};

#endif // __uhl633x0dlg__
