#ifndef __bidibdlg__
#define __bidibdlg__

/**
@file
Subclass of bidibdlggen, which is generated by wxFormBuilder.
*/

#include "bidibdlggen.h"

/** Implementing bidibdlggen */
class BidibDlg : public bidibdlggen
{
protected:
	// Handlers for bidibdlggen events.
	void OnAddNode( wxCommandEvent& event );
	void OnModifyNode( wxCommandEvent& event );
	void OnDeleteNode( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	BidibDlg( wxWindow* parent );
};

#endif // __bidibdlg__
