#ifndef __dcc232dlg__
#define __dcc232dlg__

/**
@file
Subclass of dcc232gen, which is generated by wxFormBuilder.
*/

#include "dcc232dlggen.h"

#include "rocs/public/node.h"

/** Implementing dcc232gen */
class DCC232Dlg : public dcc232gen
{
  void initLabels();
  void initValues();
  void evaluate();
  void onOK( wxCommandEvent& event );
  void onCancel( wxCommandEvent& event );
  iONode m_Props;

public:
	/** Constructor */
	DCC232Dlg( wxWindow* parent, iONode props );
};

#endif // __dcc232dlg__
