#ifndef __rocnetdlg__
#define __rocnetdlg__

/**
@file
Subclass of rocnetdlggen, which is generated by wxFormBuilder.
*/

#include "rocnetdlggen.h"

/** Implementing rocnetdlggen */
class RocNetDlg : public rocnetdlggen
{
protected:
	// Handlers for rocnetdlggen events.
	void OnSublib( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	RocNetDlg( wxWindow* parent );
};

#endif // __rocnetdlg__
