#ifndef __ucons88dlg__
#define __ucons88dlg__

/**
@file
Subclass of ucons88dlggen, which is generated by wxFormBuilder.
*/

#include "ucons88dlggen.h"

#include "rocs/public/node.h"

//// end generated include

/** Implementing ucons88dlggen */
class uConS88Dlg : public ucons88dlggen
{
  protected:
    // Handlers for ucons88dlggen events.
    void OnCancel( wxCommandEvent& event );
    void OnOK( wxCommandEvent& event );
    void OnHelp( wxCommandEvent& event );

    void initLabels();
    void initValues();
    void evaluate();
    iONode m_Props;
    const char* m_Devices;

  public:
    /** Constructor */
    uConS88Dlg( wxWindow* parent, iONode props, const char* devices=NULL );
    //// end generated class members
	
};

#endif // __ucons88dlg__
