#ifndef __uhl68610dlg__
#define __uhl68610dlg__

/**
@file
Subclass of uhl68610dlggen, which is generated by wxFormBuilder.
*/

#include "uhl68610gen.h"

/** Implementing uhl68610dlggen */
class Uhl68610Dlg : public uhl68610dlggen
{
  void initLabels();

public:
	/** Constructor */
	Uhl68610Dlg( wxWindow* parent );

	void onReporting( wxCommandEvent& event );
  void onRead( wxCommandEvent& event );
  void onWrite( wxCommandEvent& event );
  void onCancel( wxCommandEvent& event );
  void onOK( wxCommandEvent& event );

};

#endif // __uhl68610dlg__
