#ifndef __uhl633x0dlg__
#define __uhl633x0dlg__

/**
@file
Subclass of uhl633x0dlggen, which is generated by wxFormBuilder.
*/

#include "uhl633x0gen.h"

/** Implementing uhl633x0dlggen */
class Uhl633x0Dlg : public uhl633x0dlggen
{
public:
	/** Constructor */
	Uhl633x0Dlg( wxWindow* parent );
};

#endif // __uhl633x0dlg__
