#ifndef __uhl68610dlg__
#define __uhl68610dlg__

/**
@file
Subclass of uhl68610dlggen, which is generated by wxFormBuilder.
*/

#include "uhl68610gen.h"

/** Implementing uhl68610dlggen */
class Uhl68610Dlg : public uhl68610dlggen
{
public:
	/** Constructor */
	Uhl68610Dlg( wxWindow* parent );
};

#endif // __uhl68610dlg__
