#ifndef __cardlg__
#define __cardlg__

/**
@file
Subclass of CarDlg, which is generated by wxFormBuilder.
*/

#include "cardlggen.h"

#include "rocs/public/node.h"

/** Implementing CarDlg */
class CarDlg : public cardlggen
{
  iONode m_Props;
  bool   m_bSave;
  int    m_TabAlign;

  void initLabels();

public:
	/** Constructor */
  CarDlg( wxWindow* parent, iONode p_Props, bool save=true );
};

#endif // __cardlg__
