#ifndef __fxdlg__
#define __fxdlg__

/**
@file
Subclass of fxdlggen, which is generated by wxFormBuilder.
*/

#include "fxdlggen.h"

/** Implementing fxdlggen */
class fxdlg : public fxdlggen
{
protected:
	// Handlers for fxdlggen events.
	void onCancel( wxCommandEvent& event );
	void onOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	fxdlg( wxWindow* parent );
};

#endif // __fxdlg__
