#ifndef __powerctrldlg__
#define __powerctrldlg__

/**
@file
Subclass of powerctrlgen, which is generated by wxFormBuilder.
*/

#include "powerctrlgen.h"

/** Implementing powerctrlgen */
class PowerCtrlDlg : public powerctrlgen
{
protected:
	// Handlers for powerctrlgen events.
	void OnOn( wxCommandEvent& event );
	void OnOff( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	PowerCtrlDlg( wxWindow* parent );
};

#endif // __powerctrldlg__
