#ifndef __speedcurvedlg__
#define __speedcurvedlg__

/**
@file
Subclass of speedcurvedlggen, which is generated by wxFormBuilder.
*/

#include "speedcurvedlggen.h"

/** Implementing speedcurvedlggen */
class SpeedCurveDlg : public speedcurvedlggen
{
  wxTextCtrl* m_Step[28];
  wxSlider* m_SliderStep[28];

  void onStep( wxCommandEvent& event );
  void onSlider( wxScrollEvent& event );
  void onLinearize( wxCommandEvent& event );
  void onLogarithmize( wxCommandEvent& event );
  void onCancel( wxCommandEvent& event );
  void onOK( wxCommandEvent& event );


public:
	/** Constructor */
	SpeedCurveDlg( wxWindow* parent );
};

#endif // __speedcurvedlg__
