#ifndef __speedcurvedlg__
#define __speedcurvedlg__

/**
@file
Subclass of speedcurvedlggen, which is generated by wxFormBuilder.
*/

#include "speedcurvedlggen.h"

/** Implementing speedcurvedlggen */
class SpeedCurveDlg : public speedcurvedlggen
{
public:
	/** Constructor */
	SpeedCurveDlg( wxWindow* parent );
};

#endif // __speedcurvedlg__
