#ifndef __waybilldlg__
#define __waybilldlg__

/**
@file
Subclass of waybillgen, which is generated by wxFormBuilder.
*/

#include "waybilldlggen.h"

/** Implementing waybillgen */
class WaybillDlg : public waybillgen
{
public:
	/** Constructor */
	WaybillDlg( wxWindow* parent );
};

#endif // __waybilldlg__
