#!/bin/sh
#File:  MyBundle.app/Contents/MacOS/Run
mypath=`dirname "$0"`
echo $mypath
export DYLD_LIBRARY_PATH=$mypath
$mypath/Rocview -i $mypath/../../../rocdata/rocview.ini -t $mypath/../../../rocdata/trace/rocview.trace -icons $mypath/../Resources/icons/
