#!/bin/sh
#File:  MyBundle.app/Contents/MacOS/Run
mypath=`dirname "$0"`

mypath=$mypath/../../../Rocview.app/Contents/MacOS/

echo "#####"
echo $mypath
echo "#####"
export DYLD_LIBRARY_PATH=$mypath
$mypath/Rocview -modview -i $mypath/../../../rocdata/rocview.ini -t $mypath/../../../rocdata/trace/rocview.trace -icons $mypath/../Resources/icons
