/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2014 Rob Versluis, Rocrail.net

 


 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 3
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/
#ifndef __accdecdlg__
#define __accdecdlg__

/**
@file
Subclass of Accessory Decoders, which is generated by wxFormBuilder.
*/

#include "accdecgendlg.h"
#include "basedlg.h"

#include "rocs/public/node.h"


//// end generated include

/** Implementing Accessory Decoders */
class AccDecDlg : public AccDecGenDlg, public BaseDialog
{
  iONode m_Props;
  void initCVDesc();
  const char* m_CVDesc[256];
  int m_iSelectedCV;
  iONode m_CVNodes[1024];

protected:
		// Handlers for Accessory Decoders events.
		void onAdd( wxCommandEvent& event );
		void onDelete( wxCommandEvent& event );
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
		void onApply( wxCommandEvent& event );
		void onSelected( wxListEvent& event );
		void onImage( wxCommandEvent& event );
		void onDoc( wxCommandEvent& event );
		void onColClick( wxListEvent& event );
    void onCVCell( wxGridEvent& event );
    void onCVModify( wxCommandEvent& event );
    void onHelp( wxCommandEvent& event );

		void initLabels();
		bool initIndex();
		void initValues();
		bool evaluate();
	public:
		/** Constructor */
		AccDecDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __accdecdlg__
