/*
 Copyright (C) 2002-2014 Rob Versluis, Rocrail.net

 

 */
#ifndef __decconfigdlg__
#define __decconfigdlg__

/**
@file
Subclass of decconfigdlggen, which is generated by wxFormBuilder.
*/

#include "decconfigdlggen.h"

/** Implementing decconfigdlggen */
class DecConfigDlg : public decconfigdlggen
{
  int m_Config;
  void initLabels();
  void initValues();
  void onCancel( wxCommandEvent& event );
  void onOK( wxCommandEvent& event );
  void onHelp( wxCommandEvent& event );

public:
	/** Constructor */
	DecConfigDlg( wxWindow* parent, int p_Config );
	int getConfig();
};

#endif // __decconfigdlg__
