/*
 Copyright (C) 2002-2012 Rob Versluis, Rocrail.net

 Without an official permission commercial use is not permitted.
 Forking this project is not permitted.
 */
#ifndef __fxdlg__
#define __fxdlg__

/**
@file
Subclass of fxdlggen, which is generated by wxFormBuilder.
*/

#include "fxdlggen.h"

#include "wx/spinctrl.h"

/** Implementing fxdlggen */
class FxDlg : public fxdlggen
{
protected:
  int m_FX;
  wxSpinCtrl* m_CVnr;
  void initLabels();
  void initValues();
	// Handlers for fxdlggen events.
	void onCancel( wxCommandEvent& event );
	void onOK( wxCommandEvent& event );
  void onFunction( wxCommandEvent& event );

public:
	/** Constructor */
  FxDlg( wxWindow* parent, int p_FX, wxSpinCtrl* p_CVnr );
  int getConfig();


};

#endif // __fxdlg__
