/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2012 Rob Versluis, Rocrail.net

 Without an official permission commercial use is not permitted.
 Forking this project is not permitted.

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/
#ifndef __gotodlg__
#define __gotodlg__

/**
@file
Subclass of gotodlggen, which is generated by wxFormBuilder.
*/

#include "gotodlggen.h"

//// end generated include

#include "basedlg.h"

#include "rocs/public/node.h"

/** Implementing gotodlggen */
class GotoDlg : public gotodlggen, public BaseDialog
{
  void initIndex();
  iONode m_Props;

	protected:
		// Handlers for gotodlggen events.
		void onColClick( wxListEvent& event );
		void onSelected( wxListEvent& event );
		void onBlocks( wxCommandEvent& event );
		void onStages( wxCommandEvent& event );
		void onFYs( wxCommandEvent& event );
		void onTTs( wxCommandEvent& event );
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
	public:
		/** Constructor */
		GotoDlg( wxWindow* parent );
	//// end generated class members
		iONode getSelected() {return m_Props;}
	
};

#endif // __gotodlg__
