#ifndef __lococtrldlg__
#define __lococtrldlg__

/**
@file
Subclass of LocoCtrlDlgGen, which is generated by wxFormBuilder.
*/

#include "lococtrldlggen.h"

//// end generated include

/** Implementing LocoCtrlDlgGen */
class LocoCtrlDlg : public LocoCtrlDlgGen
{
	protected:
		// Handlers for LocoCtrlDlgGen events.
		void onLB1( wxMouseEvent& event );
	public:
		/** Constructor */
		LocoCtrlDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __lococtrldlg__
