/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2012 Rob Versluis, Rocrail.net

 Without an official permission commercial use is not permitted.
 Forking this project is not permitted.

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef __lococtrldlg__
#define __lococtrldlg__

/**
@file
Subclass of LocoCtrlDlgGen, which is generated by wxFormBuilder.
*/

#include "lococtrldlggen.h"

#include "rocs/public/list.h"
#include "rocs/public/map.h"
#include "rocs/public/node.h"

//// end generated include

/** Implementing LocoCtrlDlgGen */
class LocoCtrlDlg : public LocoCtrlDlgGen
{
	protected:
		// Handlers for LocoCtrlDlgGen events.
  void onLocoImg( wxCommandEvent& event );
  void onDir( wxCommandEvent& event );
  void onLocoList( wxCommandEvent& event );
  void onCancel( wxCommandEvent& event );
  void onStop( wxCommandEvent& event );
  void onBreak( wxCommandEvent& event );
  void onClose( wxCloseEvent& event );


	public:
		/** Constructor */
		LocoCtrlDlg( wxWindow* parent );
		LocoCtrlDlg( wxWindow* parent, iOList list, iOMap map, const char* locid );
	//// end generated class members

	private:
	  void OnButton(wxCommandEvent& event);
	  void OnSlider(wxScrollEvent& event);

	  iOMap m_lcMap;
    bool m_bDir;
    int m_iSpeed;
    iOList m_DlgList;
    iOMap m_DlgMap;
    bool m_bFx[36];
    int m_iFnGroup;

	  // any class wishing to process wxWindows events must use this macro
	  DECLARE_EVENT_TABLE()
};

#endif // __lococtrldlg__
