#ifndef __toursdlg__
#define __toursdlg__

/**
@file
Subclass of toursdlggen, which is generated by wxFormBuilder.
*/

#include "toursdlggen.h"
#include "rocs/public/node.h"

/** Implementing toursdlggen */
class ToursDlg : public toursdlggen
{
  iONode m_Props;
public:
	/** Constructor */
	ToursDlg( wxWindow* parent );
  ToursDlg( wxWindow* parent, iONode tour, bool save );
  iONode getProperties() { return m_Props; };
};

#endif // __toursdlg__
