#ifndef __toursdlg__
#define __toursdlg__

/**
@file
Subclass of toursdlggen, which is generated by wxFormBuilder.
*/

#include "toursdlggen.h"

/** Implementing toursdlggen */
class ToursDlg : public toursdlggen
{
public:
	/** Constructor */
	ToursDlg( wxWindow* parent );
};

#endif // __toursdlg__
