/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2012 Rob Versluis, Rocrail.net

 Without an official permission commercial use is not permitted.
 Forking this project is not permitted.

 This program is free software; you can redistribute it and/or
 as published by the Free Software Foundation; either version 2
 modify it under the terms of the GNU General Public License
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef __widgetspanel__
#define __widgetspanel__

/**
@file
Subclass of WidgetsPanel, which is generated by wxFormBuilder.
*/

#include <wx/sizer.h>
#include <wx/gdicmn.h>
#include <wx/scrolwin.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/panel.h>

#include "rocs/public/list.h"
#include "rocs/public/node.h"

//// end generated include

/** Implementing WidgetsPanel */
class WidgetsPanel : public wxScrolledWindow
{
  iOList m_Widgets;

	protected:
		// Handlers for WidgetsPanel events.
		void OnPanelSize( wxSizeEvent& event );
	public:
		/** Constructor */
		WidgetsPanel( wxWindow* parent, wxWindowID id = wxID_ANY,
		    const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxSUNKEN_BORDER|wxHSCROLL|wxVSCROLL );
    ~WidgetsPanel();
		void initView(iOList locolist);
    void updateLoco(iONode node);
    void updateLocoImg(iONode node);
    wxGridSizer* m_GridSizer;
};



#endif // __widgetspanel__
