/*
 Rocrail - Model Railroad Software

 Copyright (C) 2002-2014 Rob Versluis, Rocrail.net

 This program is free software; you can redistribute it and/or
 as published by the Free Software Foundation; either version 2
 modify it under the terms of the GNU General Public License
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#ifndef __zoomdlg__
#define __zoomdlg__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "zoomdlggen.h"

//// end generated include

/** Implementing MyFrame1 */
class ZoomDlg : public ZoomDlgGen
{
	protected:
		// Handlers for MyFrame1 events.
		void onCancel( wxCommandEvent& event );
		void onOK( wxCommandEvent& event );
    void onZoomSelect( wxCommandEvent& event );
    void onZoomEnter( wxCommandEvent& event );
    void onZoomThumb( wxScrollEvent& event );
    void onZoomRelease( wxScrollEvent& event );
    void onHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ZoomDlg( wxWindow* parent, int percent );
	//// end generated class members
		int GetValue();
	
};

#endif // __zoomdlg__
