#!/bin/sh

if [ ! -e ~/rocrail ] ; then
	mkdir ~/rocrail
fi

# Look for a rocinit.sh file generated by make install,
# giving preference to a file in the same directory
if [ -e "`dirname $0`/rocinit.sh" ] ; then
	. "`dirname $0`/rocinit.sh"
elif [ -n "`which rocinit.sh`" ] ; then
	. rocinit.sh
else
	echo "ERROR: rocinit.sh not found"
	exit 5
fi


cd $ROCRAIL_HOME

# Run Rocview in modview mode
$ROCRAIL_LIBEXECDIR/rocview $* -modview
